server:
  port: 8080
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
          max-tokens: 512
          top-p: 1.0
